### ISSUE TITLE
Not getting the "Torchbearer" badge despite one's participation in a relay being correctly recorded

### ISSUE THREAD

**Issue by tsela** [kaleissin/RelayMuseum#1]
(CALS username: Tsela)

My participation in the very first relay (the Starling's Song) and the second one (the Wisdom of Bast) are correctly recorded in the museum (see http://relaymuseum.cals.info/relay/1-the-starlings-song/_/91/ and http://relaymuseum.cals.info/relay/2-the-wisdom-of-bast/_/48/), yet it does not appear as if I have received the Torchbearer badge on CALS. Could this be due to me being known as "Christophe Grandsire-Koevoets" on CALS but only as "Christophe Grandsire" in the relay entries? (I was not yet married back then) In that case, shouldn't some kind of fuzzy matching be implemented? Or at least a way to claim a participant name? Because people do change names with time, and I don't want to be forced to use my unmarried name in CALS just to get a badge.

**Comment by kaleissin** [comment]
The museum uses whatever name was used for that specific torch, and the torch-name needs be manually "hooked up" to the user on CALS. That can be quite a bit of detective work, which is one of the reasons I'm looking for assistance. When I started the museum I copypasted torches until my wrists (and probably Arthaey's) gave out, and since I'm not a masochist, I first switched to only adding info about relays and the first torch, and then stopped altogether, because Life Intervenes, as it is prone to do.

I've hooked up Tsela in CALS with "Christophe Grandsire", but if you've used "Christophe Grandsire-Koevoets" in newer torches and these are recorded in the museum, the link must be made again (but you'd already have the badge, so it wouldn't really be necessary for that). It should pop up when the batchjob runs next time.

Ditto for conlang names: it's a copy from whatever was used for the torch. But a way to make links to languages in CALS are missing. A link from a torch-lang to a cals-lang would be more detective-work.

The museum is meant to be a museum, recording torches as they were, that particular state of language and that particular skill and mindset of the translator at that particular time. It's a time machine, a blast from the past :)

As for fuzzy matching: Main reason why not: If it does something wrong, people might get mighty mad. Bad enough that I had a bug in the badge-code that gave out too many conlanger-badges...

**Comment by tsela** [comment]
Thank you! Sorry I never got to reply to your reaction, but that mail got
lost among all the other mails I'm getting lately.

In any case I agree that fuzzy matching could lead to wrong results. Still,
it might be useful for the "detectives" that could help you on the Museum:
if no exact match is found, but a non-exact match is, this would give such
people a lead on finding out if they are indeed the same person. So as a
supporting mechanism, this could be helpful.

Anyway, thanks for all this effort. Both CALS and this museum are great
achievements! :)

Cheers,
Christophe

On 30 April 2016 at 22:58, kaleissin <notifications@github.com> wrote:

> Closed #1 <https://github.com/kaleissin/RelayMuseum/issues/1>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/kaleissin/RelayMuseum/issues/1#event-646620313>
>



-- 
Christophe Grandsire-Koevoets
President of the Language Creation Society (http://conlang.org/)

Personal Website: http://christophoronomicon.blogspot.com/
Personal Tumblr: http://christophoronomicon.tumblr.com/
